### ISSUE TITLE
[BUG] Connection sends `strategy` and `name` on update

### ISSUE THREAD

**Issue by rdark** [yieldr/terraform-provider-auth0#24]
Looks related to #9.

When using a connection with strategy `ad`, and attempting to update (e.g to add clients), provider sends along the strategy and name, and we then get back:  `400 Bad Request: Payload validation error: 'Additional properties not allowed: strategy,name'.`

Not got much spare time at the moment to submit a PR, but might do in a few weeks if you don't manage to get around to it by then.

**Comment by alexkappa** [comment]
Hi @rdark thanks for creating an issue. Could you paste a minimal `.tf` configuration that reproduces this bug?

**Comment by alexkappa** [comment]
@rdark I've had some time to look into this, pr #27 should address this issue. Please let me know if you get around to testing it.

**Comment by rdark** [comment]
Thanks @alexkappa! I should get some time tomorrow to take a look. Looks good at first glance though.
