### ISSUE TITLE
readXXX functions should fully populate resource objects

### ISSUE THREAD

**Issue by dancrumb** [yieldr/terraform-provider-auth0#7]
Right now, implementations of `readXXX` only partially populate the `ResourceData` objects.

It's tedious work, to be sure, but I think they should really be fully populating them. See, for example: https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_api_gateway_integration_response.go#L152

- [x] Clients (Applications)
- [x] Client Grants
- [x] Connections
- [x] Custom Domains
- [x] Resource Servers (APIs)
- [x] Rules
- [x] Rules Configs

**Comment by alexkappa** [comment]
Yes, absolutely. We should do this to be in line with other providers and be consistent.

**Comment by dancrumb** [comment]
I'm working on the Client resource today

**Comment by dancrumb** [comment]
At long last, the PR is complete :)

**Comment by alexkappa** [comment]
Thanks for the help on this @dancrumb !

**Comment by dancrumb** [comment]
Thanks for your patience! This is the first time I've really written any Go, so it was a bit of a slog. but I'm excited to have this functionality!
